### PR TITLE
gcc warnings removed

### PR DESCRIPTION
**Pull request by gothub-273**
removed some gcc warnings and marked changes with "gk"

### CODE REVIEW

**Comment by gothub-273** [comment]
Mostly minor changes because of gcc warnings. Replaced "extern inline" and "extern constexpr". Inserted possibly missing "test_perft();" in main routine of "chess_engine.cpp".

**Comment by lennertcl** [comment]
Why did this not get merged? Are pull requests not accepted?

**Comment by nkarve** [comment]
Sorry for the late reply everyone!

**Comment by bftjoe** [comment]
Why is this merged into hotfix-1 branch instead of main branch?

**Pull request merged**
